"""db refactoring

Revision ID: 17c7aa35dbfb
Revises: 0858619addb7
Create Date: 2024-08-19 20:36:48.770653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17c7aa35dbfb'
down_revision: Union[str, None] = '0858619addb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_avatar',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('mimetype', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_avatar_uuid'), 'user_avatar', ['uuid'], unique=True)
    op.drop_column('advertisement', 'vin_presence')
    op.drop_column('advertisement', 'price_uah')
    op.drop_column('advertisement', 'price_eur')
    op.drop_column('user', 'avatar')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('avatar', sa.VARCHAR(length=2048), autoincrement=False, nullable=True))
    op.add_column('advertisement', sa.Column('price_eur', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('advertisement', sa.Column('price_uah', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.add_column('advertisement', sa.Column('vin_presence', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_user_avatar_uuid'), table_name='user_avatar')
    op.drop_table('user_avatar')
    # ### end Alembic commands ###
