"""db init

Revision ID: bb8d2509e68e
Revises: 
Create Date: 2024-07-24 22:23:40.007273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb8d2509e68e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country',
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('uuid', sa.Uuid(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('is_deleted', sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_country_uuid'), 'country', ['uuid'], unique=True)
    op.create_table('area',
        sa.Column('country_id', sa.Integer(), nullable=False),
        sa.Column('cardinal_direction_type', sa.String(length=5), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('uuid', sa.Uuid(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('is_deleted', sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_area_uuid'), 'area', ['uuid'], unique=True)
    op.create_table('city',
        sa.Column('country_id', sa.Integer(), nullable=False),
        sa.Column('area_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('uuid', sa.Uuid(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('is_deleted', sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(['area_id'], ['area.id'], ),
        sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_city_uuid'), 'city', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_city_uuid'), table_name='city')
    op.drop_table('city')
    op.drop_index(op.f('ix_area_uuid'), table_name='area')
    op.drop_table('area')
    op.drop_index(op.f('ix_country_uuid'), table_name='country')
    op.drop_table('country')
    # ### end Alembic commands ###
